### ISSUE TITLE
Package imports successfully, but unable to change FOV

### ISSUE THREAD

**Issue by Brandon23z** [t-mat/UnitySceneViewFovControl#5]
Using Ctrl + Alt + Wheel just zooms in and out like normal.  The FoV button is in the Scene editor, the Asset settings menu is there, but FoV still doesn't change.

**Comment by t-mat** [comment]
Hi @Brandon23z ,
Could you provide your environment info such as Unity and OS version?  I'll try to reproduce your issue.

**Comment by Brandon23z** [comment]
Windows 7 64 bit and Unity 5.4.3f1

Thanks!

**Comment by t-mat** [comment]
oops 🤦‍♂️ , this project support Unity 5.5 or greater.  I'll add prerequisite for it.

**Comment by Brandon23z** [comment]
Oh okay. I downloaded 5.6.2f1 last night. You think it will work on that
one then?

**Comment by t-mat** [comment]
Thanks for the heads up.  I'm realized I've never checked this project with Unity 5.6.x.  And there was a problem with 5.6.
I've fixed it by b0f3c8a and [relesaed new version](https://github.com/t-mat/UnitySceneViewFovControl/releases/tag/0.1.10).

So technically 0.1.9 was working with 5.5 and 2017.1.
And now 0.1.10 works fine with 5.5, 5.6 and 2017.1.
Please download new version and check it.

**Comment by Brandon23z** [comment]
Hmm, now the settings menu shows in the Edit menu, but the button is not
next to Gizmos in the Scene window.

On Sun, Jun 25, 2017 at 3:24 PM, Takayuki MATSUOKA <notifications@github.com

**Comment by Brandon23z** [comment]
Wait, actually something weird is happening now. The FOV slider works for
the slave camera, which is in game, but it breaks the camera when I play
the game now. My character just rotates around the center of the map when I
move the mouse.

The Scene camera never changed FOV though. Is this what the script is
supposed to do?

**Comment by Brandon23z** [comment]
Hey Ignore my last two messages. It wasn't working because I was using Iso
camera mode. Once I started using Perspective mode, FOV works fine.

Thanks so much for your help! This is the most useful editor mod I've come
across!

On Sun, Jun 25, 2017 at 3:24 PM, Takayuki MATSUOKA <notifications@github.com

**Comment by t-mat** [comment]
Good to hear that, and again thanks for the reports !
